name: BeerPlugin
version: 2
main: beerplugin.main.BeerPluginv2
api-version:  1.13
authors: [ Mitsobabis | Vaggelis Karastergios ]
description: A plugin for my small SMP server
commands:
  uuid:
    description: saws you your uuid
    usage: /<command>
    alias: [/beeruniqueid]
  rules:
    descrprtion: saws you the rules
    usage: /<command>
    alias: []
  selfxp:
    description: gives specific players xp
    usage: /<command>
    alias: [/xpself]
  sendxp:
    description: Send someone xp idk why man
    usage: /<command>
    alias: []
  discord:
    description: shows you the discord server link
    usage: /<command>
    alias: []
  antibot:
    description: checks if some accounts are bots
    usage: /<command>
    alias: []
  cheatwarn:
    description: Warns someone for cheating
    usage: /<command>
    alias: []
  griefwarn:
    description: Warns someone for cheating
    usage: /<command>
    alias: []
  warn:
    description: Generally warns somebody
    usage: /<command>
    alias: []
  warnlist:
    description: Gives a list of warnings
    usage: /<command>
    alias: []
  track:
    description: tracks players
    usage: /<command>
    alias: []